# Generated by Django 5.2.5 on 2025-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('ssn', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_length', models.IntegerField()),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_purpose', models.CharField(max_length=255)),
                ('loan_term', models.IntegerField()),
                ('id_proof', models.FileField(upload_to='documents/id_proofs/')),
                ('income_proof', models.FileField(upload_to='documents/income_proofs/')),
                ('bank_statement', models.FileField(upload_to='documents/bank_statements/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
