# Generated by Django 5.2.5 on 2025-09-08 14:15

import client_bank.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=client_bank.models.generateAccountNumber, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=12),
        ),
    ]
