# Generated by Django 5.2.5 on 2025-09-24 13:14

import client_bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_bank', '0002_alter_account_account_number_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref',
            field=models.CharField(default=client_bank.models.generateTransactionRef, max_length=64, unique=True),
        ),
    ]
